### PR TITLE
; -> && to prevent false positive when visual tests failing

### PR DESCRIPTION
**Pull request by limonte**
The regression from https://github.com/vaadin/vaadin-element-skeleton/pull/65

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/69)

### CODE REVIEW

**Comment by platosha** [comment]
Could you please produce a build broken by visual tests with this? Maybe in a branch?

Just to verify that false positive does not occur.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/69#-:-Kxx3ln-v2biWIbeQYqn:b-k8hnvg)*

**Comment by limonte** [comment]
> Could you please produce a build broken by visual tests with this? Maybe in a branch?
> 
> Just to verify that false positive does not occur.

Sure: https://travis-ci.org/vaadin/vaadin-element-skeleton/builds/296288540

**Comment by platosha** [comment]
OK, seems broken. :thumbsup: 

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/69#-:-Kxx7FFOaPstV9bD2Rqe:bcct82n)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/69#-:-KxxEpjXqjLRMlW4pCQk:bnfp4nl)*

**Pull request merged**
