### PR TITLE
Remove Polymer references from installation instructions

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to https://github.com/vaadin/components-team-tasks/issues/420

I can create same PR to all components as well once this is merged

### CODE REVIEW

**Comment by web-padawan** [comment]
No need to submit PRs for each component. We usually review the PR in skeleton, and then push to master manually. Also, please add `[skip ci]` to commit message.

**Comment by samiheikki** [comment]
Added `[skip ci]` to commit msg

**Comment by samiheikki** [comment]
@tomivirkki can you share details for @lkraav

**Comment by web-padawan** [comment]
@lkraav the overall idea is that in future, we should iteratively move away from Polymer library (which is not recommended for using in new projects by Polymer team). 

Until then, we would like to update docs so the users don't mistakenly associate Vaadin components with Polymer Elements, which are in the maintenance mode. I agree this change is rather a compromise but it also indicates that we at least acknowledge the need for updating our technology stack.

**Pull request merged**
