### PR TITLE
Remove Polymer 2 mention

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142#-LG04O1j2AziqIW-Wpd5:-LG04FwJ9RnqOb8UtW0U:b-swxwql) (no related file):*
Good catch, I guess this got fixed in the components but skeleton was forgotten. Can you update vaadin-directory-description.md at the same time?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142#-LG04O1j2AziqIW-Wpd5:-LG05Y-AE_GrlsWPz4Au:bt8p3sd) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Good catch, I guess this got fixed in the components but skeleton was forgotten. Can you update vaadin-directory-description.md at the same time?
</blockquote></details>

Ok nevermind, vaadin-directory-description.md is wrong in the components also. Thanks for the PR

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142#-:-LG05ehFEGUsIvnyysTk:bnfp4nl)*

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142#-LG04O1j2AziqIW-Wpd5:-LG05cSa2DIw-JXh1er8:bkmb8vy) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Ok nevermind, vaadin-directory-description.md is wrong in the components also. Thanks for the PR
</blockquote></details>

This is only updating `vaadin-directory-description.md`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142#-LG04O1j2AziqIW-Wpd5:-LG0W9Je9jxI7dCXU9BN:b-tzi5uc) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

This is only updating `vaadin-directory-description.md`
</blockquote></details>

Ah, yes...indeed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/142)*

**Pull request merged**
