### PR TITLE
Verify bower dependencies

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
As requested in https://github.com/vaadin/vaadin-button/pull/99

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/162)

### CODE REVIEW

**Comment by limonte** [comment]
Doesn't work for `vaadin-grid`:

image

**Comment by SomeoneToIgnore** [comment]
If you plan to merge it in near future I can investigate and fix it.

**Comment by limonte** [comment]
> If you plan to merge it in near future I can investigate and fix it.

Yes, please go ahead.

**Comment by SomeoneToIgnore** [comment]
How do I reproduce it?
Have applied the changes to Grid's gulpfile.js, run `bower i && gulp bower:check` – worked for me.

**Comment by web-padawan** [comment]
Merging into `depcheck` branch to restart tests and for cleaner history, and will check manually agains 5.3.0-alpha of the `vaadin-grid`.

**Pull request merged**
