### PR TITLE
Split visual tests and unit tests into jobs

### PR DESCRIPTION
**Pull request by limonte**
The same as https://github.com/vaadin/vaadin-split-layout/pull/84

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/65)

### CODE REVIEW

**Comment by platosha** [comment]
S

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/65#-KxNNSe-gDaXw7a9gfv1:-KxNNSe03oYlkeJS6Lp-:b-pd1g5l) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/11b95a122d0ab10094c10ec1b14961440b28840f/.travis.yml#L38)):*
> ```YAML
>     fi
>   - if [ "$TRAVIS_EVENT_TYPE" = "cron" && "$TEST_SUITE" = "visual_tests" ]; then
>       xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs-cron;
> ```

The cron test environment is confusing.

Should here rather also be branching on `$TEST_SUITE` for `visual_tests` and `unit_tests`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/65#-:-KxNNRIsjixj-dnQzo0i:b3kry)*

**Comment by limonte** [comment]
> S

?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[.travis.yml, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/65#-KxNNSe-gDaXw7a9gfv1:-KxNRgHIK-zG0wnZEXWi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/11b95a122d0ab10094c10ec1b14961440b28840f/.travis.yml#L38)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The cron test environment is confusing.

Should here rather also be branching on `$TEST_SUITE` for `visual_tests` and `unit_tests`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/65#-:-KxNRL8NeN_as93cofiE:bo5o8fn)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/65#-:-KxgQGT2yYbbL7G-JL44:bnfp4nl)*

**Comment by tomivirkki** [comment]
Ping @limonte @platosha 
This reports false positives: https://travis-ci.org/vaadin/vaadin-element-skeleton/jobs/296173129

Revert or fix!

**Comment by platosha** [comment]
Oh, true that.

**Comment by limonte** [comment]
> Revert or fix!

Fix! https://github.com/vaadin/vaadin-element-skeleton/pull/69

**Pull request merged**
