### PR TITLE
Run P3 tests in all browsers

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to vaadin/components-team-tasks#342

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[wct.conf.js, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116#-LB532DB5hpVRYHF4gis:-LB532DB5hpVRYHF4git:bwv4v8b) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/8c2587f0ceda78e0741d0b8b3aa255af75899e3b/wct.conf.js#L14)):*
> ```JavaScript
>     ];
> 
>     const saucelabsPlatformsPolyfilled = [
> ```

If we're going to have this in all of our repos we should probably consider better naming. Edge isn't always going to be "polyfilled"

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116)*

**Comment by web-padawan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116#-LB532DB5hpVRYHF4gis:-LBKShJG9aQXHPC2xxyG:bv6uzwy) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/8c2587f0ceda78e0741d0b8b3aa255af75899e3b/wct.conf.js#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If we're going to have this in all of our repos we should probably consider better naming. Edge isn't always going to be "polyfilled"
</blockquote></details>

Would it work it I change to "saucelabsPlatformsMicrosoft" instead? Any better suggestion?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116)*

**Comment by tomivirkki** [comment]
*[wct.conf.js, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116#-LB532DB5hpVRYHF4gis:-LBKg24nE4hd7DXUxzWV:b-p7xndx) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/8c2587f0ceda78e0741d0b8b3aa255af75899e3b/wct.conf.js#L14)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Would it work it I change to "saucelabsPlatformsMicrosoft" instead? Any better suggestion?
</blockquote></details>

"saucelabsPlatformsMicrosoft" is ok for me

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116)*

**Comment by web-padawan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116#-LB532DB5hpVRYHF4gis:-LBLF_0sEfTdpNYf1J59:b-896fix) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/8c2587f0ceda78e0741d0b8b3aa255af75899e3b/wct.conf.js#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"saucelabsPlatformsMicrosoft" is ok for me
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116#-:-LBeMma8Cvd8BEKyIf5R:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/116#-:-LB081zdEWj2tzKst4mT:bg7igkv)*

**Pull request merged**
