### PR TITLE
Improve the build process

### PR DESCRIPTION
**Pull request by limonte**
Added to `before_script`:

- `gulp lint`
- quick tests in Chrome and Firefox

If one of those tasks is failing, we won't go ahead with SauceLabs tests

---

There are three main types of build we should cover:

1. Vaadin Developer pushes to the element's repo branch
2. Vaadin Developer or Contributor creates a PR
3. Build triggered by cron

---

I'll describe below how our build will work for each of those cases:

### 1. Vaadin Developer pushes to the element's repo branch

Push to a branch will trigger:

- `gulp lint`
- quick local tests in Chrome and Firefox
- if one of above tasks is failing build is getting stopped, else build triggers SauceLabs tests. SauceLabs tests won't include **Windows**/Chrome and **Windows**/Firefox. Chrome and Firefox are tested locally with Selenium WebDriver. Full set of tests is performed in cron build (see below).

### 2. Vaadin Developer or Contributor creates a PR

Ideally, Vaadin Developer creates a PR **after** successful branch build.

Creating a PR will trigger:

- `gulp lint`
- quick local tests in Chrome and Firefox

We don't want full SauceLabs tests here because:

- for Vaadin Developer they are already performed by a branch-push build
- for Contributor, we don't want them to immerse so deeply in all platforms we are supporting, quick Chrome/Firefox tests are enough. If there are any issues with other platforms, Vaadin Developers will handle it separately.

### 3. Build triggered by cron

Cron build will trigger:

- `gulp lint`
- quick local tests in Chrome and Firefox
- if one of above tasks is failing build is getting stopped, else build triggers full SauceLabs tests including **Windows**/Chrome and **Windows**/Firefox. If there are any issues with **Windows**/Chrome and **Windows**/Firefox, Vaadin Developers will handle it asap.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/13)

### CODE REVIEW

**Comment by manolo** [comment]
do this:

```
before_script:
- TRAVIS_BRANCH=quick/local-tests-in-travis xvfb-run -s '-screen 0 1024x768x24' wct -l chrome -l firefox
```

So as it runs all tests in fast browsers chrome and firefox and does not continues running saucelabs.

Then in the `script:` section you can avoid running tests in local platform because they were already done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-:-Kag_Q0dF_CfU3aeKRrw:b-c11qg5)*

**Comment by limonte** [comment]
I have no idea how it will work, but I'll try :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-:-KagaafUXdVCBah8Ey6T:b-5c2j31)*

**Comment by limonte** [comment]
A-ha, the `quick/` prefix! :) Nice trick, it works!

I also moved Shadow tests to the same job as Shady to speed up build a little more.

Now it seems smooth and nice! :)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-:-Kagivpgj3_7wvmYX6OC:bawvvl6)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-KahCrTkGbyZ3oXqqTmn:-KahCrTlpSQfjj8z2Qsd:b-aue0ks) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/.travis.yml#L21)):*
> ```YAML
>   - "if [ ${TRAVIS_EVENT_TYPE} != 'pull_request' ]; then
>       travis_retry xvfb-run -s '-screen 0 1024x768x24' wct;
>     fi"
> ```


I would use the `||` operator to have this in one line.

```
  - ([ "$TRAVIS_EVENT_TYPE" = pull_request ] || xvfb-run -s '-screen 0 1024x768x24' wct)
```

Note: 
 - the usage of `"` to check that the variable could be empty
 - consider to remove travis_retry, I think we shouldn't use it anymore because lately I have not seen cases where the third try fixed the build.

---

*[wct.conf.js, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-KahipPQyTlLZEWnl3XF:-KahipPQyTlLZEWnl3XG:b5ti163) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/wct.conf.js#L6)):*
> ```JavaScript
>       'Windows 10/chrome@55',
>       'Windows 10/firefox@50'
>     ];
> ```

I would Remove  chrome and firefox since you have tested them in local

---

*[wct.conf.js, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-Kahm_mLnuBSBRCXrrdT:-Kahm_mLnuBSBRCXrrdU:b-krbjmn) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/wct.conf.js#L8)):*
> ```JavaScript
>     ];
> 
>     var otherPlatforms = [
> ```

I would use a extra var for enabling platforms

```
    var platforms = process.env.SKIP_SAUCELABS ? [] : [
      'OS X 10.11/iphone@9.3',
    ...
```

And use it in `before_script`

```
   - SKIP_SAUCELABS=true xvfb-run -s '-screen 0 1024x768x24' wct -l chrome -l firefox

```

---

*[wct.conf.js, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-KahjTe9fPVO9PsdSIVA:-KahjTe9fPVO9PsdSIVB:b-l27yq5) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/wct.conf.js#L17)):*
> ```JavaScript
> 
>     // run SauceLabs tests for pushes, except cases when branch contains 'quick/'
>     if (process.env.TRAVIS_EVENT_TYPE === 'push' && process.env.TRAVIS_BRANCH.indexOf('quick/') === -1) {
> ```

Probably you don't need to test for push anymore since you don't run this when it's a PR, and the `quick` could be tested in `.travis.xml`

Try this:

```
   - ([[ $TRAVIS_EVENT_TYPE = pull_request || $TRAVIS_BRANCH = quick/* ]] || xvfb-run -s '-screen 0 1024x768x24' wct)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-KahCrTkGbyZ3oXqqTmn:-KalF39XjlD1EeKwau0C:b-896fix) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/.travis.yml#L21)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>


I would use the `||` operator to have this in one line.

```
  - ([ "$TRAVIS_EVENT_TYPE" = pull_request ] || xvfb-run -s '-screen 0 1024x768x24' wct)
```

Note: 
 - the usage of `"` to check that the variable could be empty
 - consider to remove travis_retry, I think we shouldn't use it anymore because lately I have not seen cases where the third try fixed the build.

</blockquote></details>

Done.

---

*[wct.conf.js, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-Kahm_mLnuBSBRCXrrdT:-KalD-z-q-9CSeXzQIB3:b8do80a) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/wct.conf.js#L8)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I would use a extra var for enabling platforms

```
    var platforms = process.env.SKIP_SAUCELABS ? [] : [
      'OS X 10.11/iphone@9.3',
    ...
```

And use it in `before_script`

```
   - SKIP_SAUCELABS=true xvfb-run -s '-screen 0 1024x768x24' wct -l chrome -l firefox

```
</blockquote></details>

This won't work as we're deciding to run or not to run SauceLabs tests **dynamically** in `wct.conf.js` depends on `TRAVIS_EVENT_TYPE`

---

*[wct.conf.js, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-KahjTe9fPVO9PsdSIVA:-KalCZwb2IUK3sW173t0:buryq0h) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c368901b8398c07172591421f0d2a8643fe2ee6d/wct.conf.js#L17)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Probably you don't need to test for push anymore since you don't run this when it's a PR, and the `quick` could be tested in `.travis.xml`

Try this:

```
   - ([[ $TRAVIS_EVENT_TYPE = pull_request || $TRAVIS_BRANCH = quick/* ]] || xvfb-run -s '-screen 0 1024x768x24' wct)
```



</blockquote></details>

We need to trigger build on push :) When you already created a PR and you push some changes you definitely want to rerun tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-:-KalUpP-SlhxdOS0Bg9y:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-Kanb1nzieSGjqEip83M:-Kanb1nzieSGjqEip83N:boa42h8) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/4c131c39e7aed2ce1a663e3b775d65883b7faf54/.travis.yml#L16)):*
> ```YAML
> before_script:
>   - gulp lint
>   - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || TRAVIS_BRANCH=quick/${TRAVIS_BUILD_ID} xvfb-run -s '-screen 0 1024x768x24' wct)
> ```

In all cases above (1, 2 and 3) you say that lint and quick-tests should be run. So, you have to remove the condition here to always run local build.

---

*[.travis.yml, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-Kanc78e1uy1-IqDuXG7:-Kanc78e1uy1-IqDuXG8:bbn0x5i) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/4c131c39e7aed2ce1a663e3b775d65883b7faf54/.travis.yml#L19)):*
> ```YAML
> 
> script:
>   - xvfb-run -s '-screen 0 1024x768x24' wct
> ```

Only in the case 2, the sauce-labs build should be skiped. So you have to move the condition here, and this line should read:

```
-  ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || xvfb-run -s '-screen 0 1024x768x24' wct)
```

Additionally, it would be ideal if wct had some parameter in order not to run local tests, only sauce ones, because local were already run in the before_script. I've not found any option, but probably we can do via some wct configuration. Not a blocking issue right now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13)*

**Comment by manolo** [comment]
Ok, after our face to face conversation I understood the point of this setup.

:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/13#-:-Kavo-s6P63jCMmqOFp2:b-rp8u3u)*

**Pull request merged**
