### PR TITLE
Add gemini visual testing

### PR DESCRIPTION
**Pull request by limonte**
Related to the last point of https://github.com/vaadin/vaadin-input/issues/3

Perform gemini tests for `push` and `cron` builds, not for `pull_request` (fast builds for contributors + not doing the same test twice for Vaadin Devs)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/18)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[.gemini.yml, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbU4BPUjQrySHgMOgV0:-KbU4BPUjQrySHgMOgV1:b59e961) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/93fa5b77a6887ea3d893fad737078c983e2624bc/.gemini.yml#L30)):*
> ```YAML
>       platform: "Windows 10"
> 
>   # The following setups don't currently work due to selenium SafatiDriver issue
> ```

Typo: "SafatiDriver"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by limonte** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gemini.yml, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbU4BPUjQrySHgMOgV0:-KbU5r7LYjfKPwQPz9k2:b-f6ny6h) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/93fa5b77a6887ea3d893fad737078c983e2624bc/.gemini.yml#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Typo: "SafatiDriver"
</blockquote></details>

oops, fixed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by Saulis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjbI2XGYeTj7gBmZ36:-KbjbI2XGYeTj7gBmZ37:bh0hq08) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/.travis.yml#L24)):*
> ```YAML
> 
> script:
>   - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || gemini test test/visual)
> ```

I guess we should only run visual tests on "push" since it requires Sauce?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by limonte** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjbI2XGYeTj7gBmZ36:-KbjeoxUY8Qal63M8kDO:bw0dk2i) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/.travis.yml#L24)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I guess we should only run visual tests on "push" since it requires Sauce?
</blockquote></details>

That's right and this is the condition for `push`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by limonte** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjbI2XGYeTj7gBmZ36:-Kbjh02OGWL-0ij9x2BO:b-ta9zjr) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/.travis.yml#L24)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

That's right and this is the condition for `push`
</blockquote></details>

sorry, for `push` or `cron`. Or even better: for any type of build except `pull_request`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by manolo** [comment]
Reviewed 2 of 12 files at r1, 8 of 14 files at r3.
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[.gemini.yml, line 31 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjmLw4GNtvoNZbqvi6:-KbjmLw4GNtvoNZbqvi7:b86hkp9) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/.gemini.yml#L31)):*
> ```YAML
> 
>   # The following setups don't currently work due to Selenium SafariDriver issue
>   # https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4136
> ```

Could we open an issue in the skeleton project 'Enable visual tests in Safari platforms when SafariDriver is fixed ' , and make a reference to the original issue?

---

*[test/visual/test.js, line 11 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjnHGQAUbp013XvQaP:-KbjnHGRuvxivH3sq1Oh:bnstlyz) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/test/visual/test.js#L11)):*
> ```JavaScript
>         this.button = find('button');
>       })
>       .capture('normal button')
> ```

I'd rather not have spaces in the name of the tests, so as folder names do not contain those spaces. It may be `normal-button` instead ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by limonte** [comment]
Review status: 3 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[.gemini.yml, line 31 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjmLw4GNtvoNZbqvi6:-KbjtdApMP_XkzJwXqbP:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/.gemini.yml#L31)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Could we open an issue in the skeleton project 'Enable visual tests in Safari platforms when SafariDriver is fixed ' , and make a reference to the original issue?
</blockquote></details>

Done

---

*[test/visual/test.js, line 11 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbjnHGQAUbp013XvQaP:-KbjtekQXbYLpPKadxz0:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/604a24de5d18f658dcef418cee6be5844f2d3e6b/test/visual/test.js#L11)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'd rather not have spaces in the name of the tests, so as folder names do not contain those spaces. It may be `normal-button` instead ?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by manolo** [comment]
Reviewed 1 of 12 files at r1, 14 of 14 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/visual/index.html, line 14 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbnCBNkblEtJpKY551w:-KbnCBNkblEtJpKY551x:b-knloz5) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c2dee89c4c79fded9559f7be13a7f3ca1692f233/test/visual/index.html#L14)):*
> ```HTML
> 
>   <span id="visual-tests">
>     <button>
> ```

For this case, could it be possible to use the same screenshots for all devices if you add some styling here in order that all buttons look the same?. For instance `font-family: sans-serif; font-size: 10px; background: white; border: solid 1px black; width: 80px; height: 20px'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/index.html, line 14 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbnCBNkblEtJpKY551w:-KbnZfec3rdce2YfQKt8:b-q13wby) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c2dee89c4c79fded9559f7be13a7f3ca1692f233/test/visual/index.html#L14)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

For this case, could it be possible to use the same screenshots for all devices if you add some styling here in order that all buttons look the same?. For instance `font-family: sans-serif; font-size: 10px; background: white; border: solid 1px black; width: 80px; height: 20px'
</blockquote></details>

Not a blocker, just a suggestion if it could simplify the skeleton.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/visual/index.html, line 14 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbnCBNkblEtJpKY551w:-Kbn_5D5hLN4DOnsKTzX:b-8v4f90) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c2dee89c4c79fded9559f7be13a7f3ca1692f233/test/visual/index.html#L14)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Not a blocker, just a suggestion if it could simplify the skeleton.
</blockquote></details>

Even with same styles screenshots will be different in pixels because of rendering, anti-aliasing, and all that OS-related and browser-engine-related shit :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/visual/index.html, line 14 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-KbnCBNkblEtJpKY551w:-Kbng-hbXT6HkiM5KuZ-:brgurbg) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c2dee89c4c79fded9559f7be13a7f3ca1692f233/test/visual/index.html#L14)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Even with same styles screenshots will be different in pixels because of rendering, anti-aliasing, and all that OS-related and browser-engine-related shit :)
</blockquote></details>

Thanks for the clarification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/18#-:-Kbng3PmmY6qjaAn5JyB:b-uwkowd)*

**Pull request merged**
