### PR TITLE
Use files property of package.json instead of .npmignore

### PR DESCRIPTION
**Pull request by limonte**
`.npmignore` is a bad idea because developers need to keep it in mind on every change in files/folders structure and it's very easy to forget it and to start publishing things end-users don't need at all (e.g. visual tests screenshots)

Docs: https://docs.npmjs.com/files/package.json#files

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/111)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/111#-:-L9oLjzx8sQLc_RJTdHc:bnfp4nl)*

**Comment by limonte** [comment]
The same thing just got merged into polymer: https://github.com/Polymer/polymer/commit/eb84ea0422824b2539fc0c4a1bf3d40eb9899fb8

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/111#-LK1Glz-A_-XRkJ5ck2u:-LK1Glz-A_-XRkJ5ck2v:b-e3lact) (no related file):*
Are tests and demos needed in the published package?

---

**Comment by tomivirkki** [comment]
Considering https://github.com/vaadin/vaadin-grid/issues/1374, should readme be included in the file list also?

**Comment by limonte** [comment]
> Considering vaadin/vaadin-grid#1374, should readme be included in the file list also?

From https://docs.npmjs.com/files/package.json#files

> Certain files are always included, regardless of settings:
>
> package.json
> README
> CHANGES / CHANGELOG / HISTORY
> LICENSE / LICENCE
> NOTICE
> The file in the "main" field
>
> README, CHANGES, LICENSE & NOTICE can have any case and extension.

**Pull request merged**
