### PR TITLE
Add IE11 support

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/32)

### CODE REVIEW

**Comment by Saulis** [comment]
IE11 tests seem to be timing out consistently, tried running 3 times in a row.

**Comment by tomivirkki** [comment]
wct needs to be upgraded to 6. 5 doesn't use polyserve.

**Comment by limonte** [comment]
> wct needs to be upgraded to 6. 5 doesn't use polyserve.

Done, thx!

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/32#-:-KhbEeLgop4yxHJmTBFC:bnfp4nl)*

**Pull request merged**
