### PR TITLE
Added Vaadin Directory badges

### PR DESCRIPTION
**Pull request by binhbbbb**
Connected to https://github.com/vaadin/components-team-tasks/issues/351

I have added a `published` badge and a `rating` badge. 
  
The URL Identifier is `vaadinvaadin-grid` in this URL https://vaadin.com/directory/component/vaadinvaadin-grid
  
Just replace `vaadin-element-directory-urlidentifier` with that.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/115)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 6 at r1](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/115#-LBKaXgK8387VvBjYVGk:-LBKaXgK8387VvBjYVGl:b-ww4e9y) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/c548ffeabcfc818e0da1499afc75fdc387f01987/README.md#L6)):*
> ```Markdown
> [Gitter](https://gitter.im/vaadin/web-components?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
>   
>  [Published on Vaadin  Directory](https://vaadin.com/directory/component/vaadin-element-directory-urlidentifier)
> ```

Hello @binhbbbb and thanks for this PR! 

This repository is used by us for automation for creating new components. Here's the guide how to do that: https://github.com/vaadin/vaadin-element-skeleton/blob/master/README_CREATE_NEW.md

In the guide you can find `perl -pi -e 's,vaadin-element,new-element-name,g' *.* demo/* test/* src/* theme/*/*` which means that all `vaaidin-element` entries will be replaced by the new element name.

According to that, `vaadin-element-directory-urlidentifier` should be replaced by `vaadinvaadin-element` in this line and the line below.

After that, the PR is good to go!

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/115)*

**Comment by binhbbbb** [comment]
Oh my, I'm such a donkey.

P/s: What do you mean by different Git credentials? AFAIK, I'm using the same account to make two commits.

**Comment by limonte** [comment]
> AFAIK, I'm using the same account to make two commits.

Nope:

**Comment by binhbbbb** [comment]
Oh yeah, I was changing my GitHub username a few days ago. I hope no trouble here.

**Pull request merged**
