### PR TITLE
Remove header from 'live demo' link

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/4)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4#-KYwtifoBRYyVPKJD5A7:-KYwtifoBRYyVPKJD5A8:b95hdlb) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/77d32023c0178ff93b4be61e6c6bd512aaec787f/README.md#L8)):*
> ```Markdown
> # &lt;vaadin-element&gt;
> 
> <a href="https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-element/demo/" target="_blank">Live Demo </a>
> ```

At the same time could you move it to the last position in the section, just after the screenshot.

Also, probably there is a unicode character similar to this icon that we can use instead of trust in a external image that we dont control

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4#-KYwtifoBRYyVPKJD5A7:-KYx0hM6xTFtPlm0LdEc:bl1auwg) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/77d32023c0178ff93b4be61e6c6bd512aaec787f/README.md#L8)):*
> At the same time could you move it to the last position in the section, just after the screenshot.

I disagree with this. `Live Demo` should be visible for user right away.

>  probably there is a unicode character similar

There's no as far as I know.

> external image that we don't control

This image is alive for [more than 3 years](http://stackoverflow.com/a/20756328/1331425), so I believe it will be available in near future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4#-KYwtifoBRYyVPKJD5A7:-KYxAe9myE2Dmp4kBQxd:b3zm4qe) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/77d32023c0178ff93b4be61e6c6bd512aaec787f/README.md#L8)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> At the same time could you move it to the last position in the section, just after the screenshot.

I disagree with this. `Live Demo` should be visible for user right away.

>  probably there is a unicode character similar

There's no as far as I know.

> external image that we don't control

This image is alive for [more than 3 years](http://stackoverflow.com/a/20756328/1331425), so I believe it will be available in near future.
</blockquote></details>

I replaced the image by ↗

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4#-KYwtifoBRYyVPKJD5A7:-KZ0F-1aSnbvLs_3l1iD:biu3xgz) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/77d32023c0178ff93b4be61e6c6bd512aaec787f/README.md#L8)):*
> I disagree with this. Live Demo should be visible for user right away.

Well, my point was that in the webcomponents.org repo there this seems to be a redundant link to the demo, since the natural way to see live demos is by clicking on the right menu link since it's shown inside the site instead of  bringing the user out of the site.

Anyway there are other components with the demo link at top as well linking to their website, so It's ok to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/4#-:-KZ0HJfssvT7at9ho8Hg:bnfp4nl)*

**Pull request merged**
