### PR TITLE
npm 5 :tada:

### PR DESCRIPTION
**Pull request by limonte**
http://blog.npmjs.org/post/161276872334/npm5-is-now-npmlatest

image

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/37)

### CODE REVIEW

**Comment by limonte** [comment]
In case this change will be approved and merged I will:

 - replace `yarn` by `npm5` for all components where `yarn` is used
   - remove `yarn.lock`
   - add `package-lock.json`
 - add `package.json.lock` for all components where `npm` is used

**Comment by samiheikki** [comment]
@limonte is npm5 faster (or as fast) than yarn? If it is then I think we should get rid of yarn and add this fix to all of our elements.

**Comment by limonte** [comment]
> is npm5 faster (or as fast) than yarn? 

Speed results for `npm5` and `yarn` are pretty the same.

>  If it is then I think we should get rid of yarn and add this fix to all of our elements.

Yup, that's what I wrote in the [comment above](https://github.com/vaadin/vaadin-element-skeleton/pull/37#issuecomment-305708626).

**Comment by limonte** [comment]
Done in #38

**Pull request closed without merging**
