### PR TITLE
Remove Bower caching

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/10)

### CODE REVIEW

**Comment by platosha** [comment]
Why? This is a feature, not a bug.

**Comment by limonte** [comment]
https://www.flowdock.com/app/vaadin/elements-team/threads/D8Sg4h3l0ISfWsqrQ64DSiyxATc

**Comment by platosha** [comment]
Having just one case when caching not applies after a major dependency update is not enough, IMO, to switch the caching off everywhere.

Clearing the cache once should work just fine for this case. It should then create the branch cache, different from the master cache, which will work for the subsequent branch builds and speed them up.

**Comment by limonte** [comment]
> when caching not applies

Caching applies, but incorrectly and create a big WTF because it's totally unclear for developer why the same configuration works locally and doesn't work in Travis. 

There will **surely** be similar situations in future, this is the right time to close this source of WTFs.

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-skeleton/10)*

**Pull request merged**
