### PR TITLE
use wct-config-vaadin

### PR DESCRIPTION
**Pull request by vlukashov**
Most Vaadin components use Web Component Tester to run tests. Every repo has its own copy of the WCT config and that leads to inconsistencies (especially in the list of SauceLabs platforms). It would be easier to maintain and update the WCT configs in all Vaadin Components if they were using the same default WCT config as a base.

There are 2 PRs and 1 new repo that together make up this change:
 - create a new npm package / new GitHub repo to keep the default Vaadin Web Component Tester config: https://github.com/vaadin/wct-config-vaadin
   _It needs to be released to npm first before the PRs can be merged._
 - update the `vaadin-component-dev-dependencies` meta package to include `wct-config-vaadin`: https://github.com/vaadin/vaadin-component-dev-dependencies/pull/2
 - [this PR] update `vaadin-element-skeleton` to use the WCT config from the `wct-config-vaadin` package: https://github.com/vaadin/vaadin-element-skeleton/pull/164

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/164)

### CODE REVIEW

**Comment by web-padawan** [comment]
I was thinking of this package and have several notes:

1. In grid and overlay, we split jobs and run those separately, see relevant code:
https://github.com/vaadin/vaadin-grid/blob/54b71b8021afc5c0935dc84f8369f0a4bee7a0a7/wct.conf.js#L19

So, it would be nice to export these additionally.
```
    const saucelabsPlatformsMobile = [
      'iOS Simulator/iphone@11.3',
      'iOS Simulator/iphone@9.3'
    ];

    const saucelabsPlatformsMicrosoft = [
      'Windows 10/microsoftedge@17',
      'Windows 10/internet explorer@11'
    ];

    const saucelabsPlatformsDesktop = [
      'macOS 10.13/safari@11.1'
    ];
```
2. We need to configure thresholds per each component, it would be nice to make it simpler (note the value is quite deep and could be passed also as a parameter)

3. we have disabled headless Firefox in certain components where it caused timeouts in CI

**Comment by limonte** [comment]
Sorry about the delayed reply!

Even though, I like the idea behind this PR, I will close it because it requires some additional effort in order to support all cases @web-padawan mentioned.

We are now prototyping the new skeleton which will use karma instead of wct: https://github.com/vaadin/vaadin-element-skeleton/pull/182 so it doesn't make much sense to put resources into the improvement of a current skeleton structure. The PR I linked is ready for review, feel free to check it out and leave you suggestions/ideas there.

**Comment by vlukashov** [comment]
If the idea of a shared WCT config is discarded, then could you please close the other 2 parts of it?
 - vaadin/vaadin-component-dev-dependencies#2 - close the PR
 - https://github.com/vaadin/wct-config-vaadin - archive the repo

**Comment by limonte** [comment]
Done 👍

**Pull request closed without merging**
