### PR TITLE
Ensure Polymer 3 Modulizer compatibility

### LINKED ISSUE #108: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #108

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/110)

### CODE REVIEW

**Comment by web-padawan** [comment]
Please also implement following points from the document:

- Ensure for demo/index.html HTML imports are listed under `<head>` before `<custom-style>`, not `<body>`
- Ensure there is vaadin-demo-ready-event-emitter.js script line in demo/index.html head:
`<script src=”../../vaadin-demo-helpers/vaadin-demo-ready-event-emitter.js”></script>`
- Convert demo/element-demo.html to sync js file with window.ElementDemo definition. Replace HTML import in demo/index.html with demo/element-demo.js script.

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bower.json, line 27 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/110#-L8fVJNz61a4DQC2bvnt:-L8fVJO-CKgaar7sUSdG:barruhw) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/9b756d26e9243edbf301d70ba7091ddfb907e583/bower.json#L27)):*
> ```JSON
>   "dependencies": {
>     "polymer": "^2.0.0",
>     "vaadin-themable-mixin": "p3-preview"
> ```

consider using the same notation as we have in the components:
``` 
"vaadin/vaadin-themable-mixin#p3-preview"
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/110#-:-L8fVsdEDwmIkJud-g95:b-qnccr9)*

**Comment by YuriyVaadin** [comment]
@web-padawan , done.

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 27 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/110#-L8fVJNz61a4DQC2bvnt:-L8fayr38sibMwT1xva-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/9b756d26e9243edbf301d70ba7091ddfb907e583/bower.json#L27)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider using the same notation as we have in the components:
``` 
"vaadin/vaadin-themable-mixin#p3-preview"
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/110#-:-L8fazAfE7nBufA9W8yT:bbem00q)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/110#-:-L8fbV-N7txUHR74-v2x:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 3 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/110#-:-L8gG6Tp76lts3ng_DTZ:bnfp4nl)*

**Pull request merged**
