### PR TITLE
Use stable polymer-cli for P2, prevent false-positives

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to vaadin/components-team-tasks#333

See also polymer/polymer-cli#987

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/112)

### CODE REVIEW

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/112#-:-L9FvC2mC3ZUqSL90tZH:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm: Firefox still only gets tested on `pull_request`s though. Should add the missing `Windows 10/firefox@59` to `saucelabsPlatforms` (can be done in a separate PR)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/112#-:-L9FzZRg5G-wLPEePa9r:b-vre622)*

**Comment by web-padawan** [comment]
> Should add the missing Windows 10/firefox@59 to saucelabsPlatforms (can be done in a separate PR)

Done. Added Chrome for P2 tests as well, we actually have it in most of `

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/112#-:-L9GFO0C9zl5j8bjoWU5:b-v7c3kw)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-skeleton/112)*

**Pull request merged**
