### PR TITLE
Change distro to xenial to get chrome stable

### PR DESCRIPTION
**Pull request by alvarezguille**

### CODE REVIEW

**Comment by web-padawan** [comment]
See also webcomponets/polyfills#200

**Comment by Haprog** [comment]
> See also [webcomponents/polyfills#200](https://github.com/webcomponents/polyfills/pull/200)

@web-padawan At least the local tests (chrome, firefox) seem to work in the PR CI just changing the `dist`. Do you know should we do those other changes or what they do? (moving from `xvfb-run` to `services: - xvfb` and using the extra `apt` source and package?

I guess the extra `apt` config can get latest Chrome versions faster if the default (with current config) uses default sources from the distro?

**Comment by Haprog** [comment]
SauceLabs tests seem to fail with errors like:
```
macOS 10.13 safari latest Tests failed: Timed out
macOS 10.13 safari latest Failed to quit: ERROR The test with session id c5b687938c254d51af883c3d8820cfcf has already finished, and can't receive further commands.
You can learn more at https://app.saucelabs.com/tests/c5b687938c254d51af883c3d8820cfcf
For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
```

Screen recording of SauceLabs run shows
image

**Comment by Haprog** [comment]
It seems that the above SauceLabs error only happens every time on `bionic`. I guess on `bionic` there's some problem preventing SauceLabs to connect to Travis via socket. If using `xenial` instead, then all tests seem to pass normally (PR local browsers and SauceLabs). I tested this in a `vaadin-date-time-picker` [PR](https://github.com/vaadin/vaadin-date-time-picker/pull/7) by first switching it to `bionic` and then to `xenial`.

**Pull request merged**
