### PR TITLE
chore: update to latest dependencies and gulp 4

### PR DESCRIPTION
**Pull request by web-padawan**

### CODE REVIEW

**Comment by tomivirkki** [comment]
Is this urgently required for something? Would prefer dropping gulp and switching to node scripts instead.

**Comment by web-padawan** [comment]
I'm ok with switching to node scripts, too. That will need a bit more effort though.

**Comment by Haprog** [comment]
Would be nice to get the updated deps (or mainly `eslint-plugin-html@^5.0.0`) so that ESLint would start working in e.g. VS Code without having to manually run `npm i --no-save eslint-plugin-html@^5.0.0` in every repo.

But I'm fine with this workaround for now as long as we would get rid of this problem preferably in the near future.

**Comment by web-padawan** [comment]
Closing, gulp to be removed in #199

**Pull request closed without merging**
