### PR TITLE
[WIP] Use Selenium instead of SauceLabs for visual tests, SauceLabs is instable

### PR DESCRIPTION
**Pull request by limonte**
As per recent discussions about the instability of visual tests with SauceLabs.

This PR is mainly made by @manolo as well as the `gemini-selemium` plugin: https://github.com/manolo/gemini-selenium

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @limonte)

---

*[.gemini.yml, line 17 at r1](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133#-LEiF3Nd5Ixsu0vVnS3v:-LEiF3Nd5Ixsu0vVnS3w:b-qwnaxb) ([raw file](https://github.com/vaadin/vaadin-element-skeleton/blob/2c1cee0f60397e16af454730782cd976b66782cd/.gemini.yml#L17)):*
> ```YAML
>       chromeOptions:
>         args:
>           - headless
> ```

It might be very useful if we test mobile in chrome at the same round, mind to give a try ? 


```
  chrome-phone:
    desiredCapabilities:
      browserName: 'chrome'
      chromeOptions:
        mobileEmulation:
          deviceMetrics:
            width: 320
            height: 568
            pixelRatio: 1
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133#-LEiIG0TDgq0BFzc2iAv:-LEiIG0TDgq0BFzc2iAw:bmjjhbs) (no related file):*
What about testing shady?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @limonte)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133#-LEiIG0TDgq0BFzc2iAv:-LEiR2_BBBaE6w_tZpsU:bma2trp) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

What about testing shady?
</blockquote></details>

I couldnt make FF work in my mac, even downgrading to 47 as it's run in sauce. I have not tried in linux. But for mac other ppl is experimenting the issue

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-skeleton/133)*

**Comment by limonte** [comment]
Closing this PR as the Selenium solution is the OS-dependant and screenshots are different for different platforms.

**Pull request closed without merging**
